### ISSUE TITLE
CLI sending a large number of `True` and `False` messages to console when running `upstream-prod` on `dbt-bigquery`

### ISSUE THREAD

**Issue by garfieldthesam** [LewisDavies/upstream-prod#2] opened 2023-02-01 18:35 UTC
Absolutely love this package, but the one issue is that now the console returns a large number of `True` and `False` messages when running `dbt` commands, including `run`, `build`, and `compile`. For example see this (sanitized) output from the Github CI run for the PR where I integrate this package into my repo. 

This example is from `dbt-bigquery`, so obviously not a connector the package has been verified with. 

Any idea what might be causing this issue? I might like to try my hand at submitting a fix if there's a likely culprit. 

```
18:24:22  Found X models, Y tests, Z snapshot, A analyses, B macros, C operations, D seed files, E sources, F exposures, G metrics
18:24:22  
18:24:28  Concurrency: 2 threads (target='target_name')
18:24:28  
18:24:29  1 of X START sql table model schemaname.tablename  [RUN]
18:24:29  2 of X START sql table model schemaname.tablename  [RUN]
18:24:29  False
18:24:29  False
18:24:29  False
18:24:29  False
18:24:37  2 of X OK created sql table model schemaname.tablename  [CREATE TABLE (3.5m rows, 277.1 MB processed) in 8.86s]
18:24:37  3 of X START sql incremental model schemaname.tablename  [RUN]
18:24:37  False
18:24:38  False
18:24:38  False
18:24:57  3 of X OK created sql incremental model schemaname.tablename  [CREATE TABLE (3.7m rows, 7.9 GB processed) in 20.04s]
18:24:57  4 of X START sql incremental model schemaname.tablename  [RUN]
18:24:57  False
```

**Comment by LewisDavies** [comment] 2023-02-02 12:25
Thanks for catching this @garfieldthesam - not quite sure how I managed to miss it! Also great to hear it's working with BigQuery.

It's caused by a [logging call](https://github.com/LewisDavies/upstream-prod/blob/b285e5e31c314da798d4b194867d8fd652f8448c/macros/ref.sql#L25) I forgot to remove before the latest update. You're welcome to open a PR removing the line (you can also update the version number in `dbt_project.yml` to `0.2.1` if you want) and I'll release the changes as soon as they're merged. Let me know if there's anything I can help with.

**Comment by garfieldthesam** [comment] 2023-02-02 22:53
Thanks! See PR [here](https://github.com/LewisDavies/upstream-prod/pull/3)!

**Closed** 2023-02-03 10:13 UTC
